### ISSUE TITLE
is it possibleto to use vuex in content script?

### ISSUE THREAD

**Issue by weituotian** [Kocal/vue-web-extension#282]
if the content script can get the data from vuex shared with background.js, it is so wonderful. ooop!

**Comment by Kocal** [comment]
Yes it is, I already tried [vuex-webextensions](https://github.com/MitsuhaKitsune/vuex-webextensions) and it works pretty well (except on Firefox :eyes: ping @MitsuhaKitsune)

**Comment by MitsuhaKitsune** [comment]
I develop on Firefox and I can use store from content scripts but with https://github.com/mozilla/webextension-polyfill, im working on crossbrowser compatibility without use mozilla webextension-polyfill, on https://github.com/MitsuhaKitsune/vuex-webextensions/commit/b6e66f2f1c086d498264598484c95b984ab6c8bc I implement own polyfills, only connection methods remain on polyfills because I'm reworking the sync system a bit to resolve https://github.com/MitsuhaKitsune/vuex-webextensions/issues/1 and https://github.com/MitsuhaKitsune/vuex-webextensions/issues/2

I gona work today on it and try to finish this pending stuff, then I release the 1.1.2 that should be fully compatible with Firefox too.

**Comment by Kocal** [comment]
Oh great, I'm sooo impatient to see this 😄

**Comment by MitsuhaKitsune** [comment]
I still working but I finish the polyfills, so I publish the 1.1.2 that should solve all problems with Firefox without break anything on Chrome and possible solve all on Edge too but I not tested yet on it.

If some problem exist just say to me here or fill a issue on repository, thanks for the report ^^

**Comment by MitsuhaKitsune** [comment]
@weituotian You can, there are a example image:

![vuex-webext](https://user-images.githubusercontent.com/34917786/43744473-821f9a42-99da-11e8-90d2-17c9796ab910.gif)

The timer are mutated by the background script each second and get synced properly on content script and popup.

About the counter, before I start to increment it through popup script, the value it's 28 on content and popup, I click the button 8 times, get wrong value rendered on popup because a bug that I working on it now, but you can check that content script get his correct value at the end (28 + 8 = 36).

**Comment by MitsuhaKitsune** [comment]
Crazy loop mutations solved on 693ad08 (version 1.2.0 on npm), all should work as expected now ^^

**Comment by weituotian** [comment]
wonderful! well design vuex plugin, I am using it.

**Comment by zhandao** [comment]
well done!
