### ISSUE TITLE
Upgrade to Vue CLI 3

### ISSUE THREAD

**Issue by GLaDOS1105** [Kocal/vue-web-extension#315]
If we upgrade this remote preset to Vue CLI 3 preset format, a developer could add Vue CLI 3 packages, such as [Vuetify](https://vuetifyjs.com), without using [the global bridge](https://cli.vuejs.org/guide/creating-a-project.html#pulling-2-x-templates-legacy) to Vue CLI 2.

**Comment by Kocal** [comment]
Thank for the proposal. 
At the moment there is already [adambullmer/vue-cli-plugin-browser-extension](https://github.com/adambullmer/vue-cli-plugin-browser-extension) which do what you suggest.

I don't know if it's useful to upgrade to Vue CLI 3, because if we do, that means that this project will only do:
- setup a boilerplate for `manifest.json`, `background.js`, `icons` / `popup` folders
- a script to remove `eval` usage in bundles
- a script to package the extension into a `.zip` file

this is a small part of what `adambullmer/vue-cli-plugin-browser-extension` do, so I don't think it's useful to upgrade to Vue CLI 3

**Comment by Kocal** [comment]
Hi!

Just to let you know, I'm currently transforming this Vue CLI 2 boilerplate to a Vue CLI 3/4 preset around [adambullmer/vue-cli-plugin-browser-extension](https://github.com/adambullmer/vue-cli-plugin-browser-extension), see #622.
