### ISSUE TITLE
How to add global css?

### ISSUE THREAD

**Issue by kernelogic** [Kocal/vue-web-extension#359]
Hello, I added bootstrap-vue dependency to my project based on this and it seems loading bootstrap fine. However I want to add some global css as foundation, I tried to create a popup_global.css alongside popup.html and put my css in there and it does not seem to load at all, got 404.

`<link rel="stylesheet" href="popup_global.css">`

**Comment by Kocal** [comment]
That's because `popup_global.css` is not copied during the build I guess.

There is two solution:
1. In your `popup/App.vue`, add the line `<style src="./popup_global.css">`
2. In your `webpack.config.js`, add the line `{ from: 'popup/popup_global.css', to: 'popup/popup_global.css' }` [here](https://github.com/Kocal/vue-web-extension/blob/master/template/webpack.config.js#L64)

**Comment by kernelogic** [comment]
Thank you. I used second option.
