### ISSUE TITLE
ERROR in ./popup/App.vue?vue&type=script&lang=js&

### ISSUE THREAD

**Issue by JRakhimov** [Kocal/vue-web-extension#362]
**Describe the bug**
Error occures with special part of code, without method getTime everything is okay (but build command is throwing error too, error with Terser and minify)

**Screenshots**
![err](https://i.ibb.co/swn4z1K/1.png)

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: 1.9.0
 - OS: Windows 10
 - Node.js version: v8.11.3

**Comment by JRakhimov** [comment]
@Kocal You are my hero :D. You are right I have installed core-js and now all right, buuuut npm run build thorws error
![error](https://i.ibb.co/bB1psq0/2.png)

**Comment by Kocal** [comment]
This issue is due to Terser, refs:
  - https://github.com/webpack-contrib/terser-webpack-plugin/issues/66
  - https://github.com/terser-js/terser/pull/254

Version 3.16.1 has been released, try to update `terser` dependency (https://github.com/terser-js/terser/pull/254#issuecomment-460228890) and it should works.

**Comment by JRakhimov** [comment]
`npm install terser@3.16.1 --save-dev` Thank you)
