### ISSUE TITLE
Cant load images

### ISSUE THREAD

**Issue by frzkhan** [Kocal/vue-web-extension#466]
Trying to load images like this
`<img src="../icons/icon.png">` 
but it doesnt load and i dont see any errors either

What is the correct way to load image, usually we have @ alias in vue configuration, i couldnt find it in the webpack config so i added it like below

```
resolve: {
    extensions: ['.js', '.vue'],
    alias: {
      '@': path.resolve(__dirname + '/src'),
    }
  },
```
it moves the files to the root directory and the image location in the extension changes to `/popup/icon.png` which is wrong

I'm not good at webpack, maybe i did something wrong

**Comment by uche1** [comment]
I'm also having this issue and I don't know how to fix it.

@frzkhan Did you eventually find a solution to your issue?

**Comment by frzkhan** [comment]
no, but as a workaround i put my images on cloud (aws s3) and used them in the extensions

**Comment by UchennaOkafor** [comment]
I figured it out, try this
`<img src="/icons/icon.png">`

It doesn't matter which folder you're in, that's how images are accessed for this template. No need to traverse the directory with the ../../

**Comment by Kocal** [comment]
Hi, sorry for the big delay, I was really busy those last weeks...

I was able to reproduce, determine, and fix the issue _properly_.
Given you have:
- a `popup` folder
- an image `popup/image.jpg`
- a file `popup/App.vue` which contains `<img src="./image.jpg">`

Webpack will replace this code by `<img src="image.jpg">` and so the popup will try to load `chrome-extension://<id>/popup/image.jpg`.
But this can't work because your image is located at `chrome-extension://<id>/image.jpg`.

To fix this, I've updated the images loader options by adding `outputPath: '/'`.
This way, webpack will change to `<img src="/image.jpg">` and this will work because your image is located at `chrome-extension://<id>/image.jpg`.

Also I think we can actually use outputPath: '/images/` which is a bit cleaner.

I'm opening a PR.
