### ISSUE TITLE
options_page warning in Firefox

### ISSUE THREAD

**Issue by akkhil7** [Kocal/vue-web-extension#636]
**Describe the bug**
`  "options_page": "options/options.html", ` doesn't work on firefox anymore.
```
Warning details

Reading manifest: Warning processing options_page: An unexpected property was found in the WebExtension manifest.

```

**To Reproduce**
 - Load the extension in Firefox 80.01

**Expected behavior**
 - Should load the extension without warnings.

**Solution**
Use `"options_ui"` instead - works in both Chrome and Firefox.

**Comment by akkhil7** [comment]
I can open a PR. Would like to hear your thoughts first.

**Comment by Kocal** [comment]
Hi!

I'm not sure where your issue came from, or where do you want to open a PR.

The old Vue-CLI 2 boilerplate already use `options_ui` (see https://github.com/Kocal/vue-web-extension/blob/v1/template/src/manifest.json#L19), and the new Vue-CLI 3+ preset, which use [vue-cli-plugin-browser-extension](https://github.com/adambullmer/vue-cli-plugin-browser-extension) also use `options_ui` (see https://github.com/adambullmer/vue-cli-plugin-browser-extension/blob/master/generator/template/base-app/src/manifest.json)

What's your `manifest.json` looks like?

**Comment by akkhil7** [comment]
Hi @Kocal,

I am so sorry, Hugo. I just looked up the commit history for my extension. And seems like it changed to `options_page` at some point by accident. My bad.

I am closing this issue. Thank you for prompt reply 👍  :)

Kudos to this great boilerplate, by the way. Thanks a bunch!

Cheers!

**Comment by Kocal** [comment]
Don't worry, it can happens to everyone 😝

Have a good weekend! :)
