### ISSUE TITLE
Typescript not working due eslint

### ISSUE THREAD

**Issue by djob** [Kocal/vue-web-extension#644]
Anybody got a eslint-loader error on .ts files?
```
Module parse failed: Unexpected token (2:8)
File was processed with these loaders:
 * ./node_modules/eslint-loader/index.js

```

how to disable eslinter on .ts files?

_Originally posted by @djob in https://github.com/Kocal/vue-web-extension/issues/643#issuecomment-729294417_

**Comment by Kocal** [comment]
Hi,

Your issue is caused by https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-eslint/index.js#L45

If you really want to disable `eslint-loader` on TypeScript files (which I don't really understand), you have to modify the webpack configuration with the [chaining API](https://cli.vuejs.org/guide/webpack.html#chaining-advanced).
Using the following line should do the job:
```js
config.module.rule('eslint').test(/\.(vue|jsx?)$/);
```

**Comment by djob** [comment]
Didn't manage to solve following eslint issue i had:
![image](https://user-images.githubusercontent.com/818443/100484538-20cb8500-30fd-11eb-915a-920e37b98565.png)

I had to declare a "PanelService" variable in Windows interface. As result, eslint was not accepting it.

**Comment by Kocal** [comment]
Yes, because you have to configure ESLint to process TypeScript files.

**Comment by ramsrib** [comment]
Any plans to add typescript support?

**Comment by Kocal** [comment]
You can open a feature request on https://github.com/adambullmer/vue-cli-plugin-browser-extension
