### ISSUE TITLE
Error Fetching Preset

### ISSUE THREAD

**Issue by ogurinkaben** [Kocal/vue-web-extension#649]
**Describe the bug**
I am using the vue-web-extension for the first time and after running
``` bash
vue create --preset kocal/vue-web-extension my-extenion
```
I get the following error
``` bash
npm ERR! Unexpected end of JSON input while parsing near '...+49QIlMmAWamTfDg\n+4A'

```
**To Reproduce**
1. Open a terminal terminal and run the installation command ```vue create --preset kocal/vue-web-extension my-extenion```

**Expected behavior**
Not sure of the expected behaviour, it's my first time working with the preset

**Screenshots**
![image](https://user-images.githubusercontent.com/36845308/102915293-d500c700-4481-11eb-9e4e-ee657b54e99c.png)

**Desktop (please complete the following information):**
- [vue-web-extension](https://github.com/Kocal/vue-web-extension) version: Latest
 - OS: Linux Mint 20
 - Node.js version: v10.19.0

**Comment by Kocal** [comment]
Hi!

I don't think this is related to this preset particulary, since the preset and packages are handled by Vue-CLI.

Note that I was able to initialize a new extension:
![image](https://user-images.githubusercontent.com/2103975/102945818-2c715800-44bf-11eb-9218-a7e7538de9e8.png)

Maybe it's coming from your npm/yarn version, or your internet connection. 

What happens if you try again?

**Comment by ogurinkaben** [comment]
Same thi

> Hi!
> 
> I don't think this is related to this preset particulary, since the preset and packages are handled by Vue-CLI.
> 
> Note that I was able to initialize a new extension:
> ![image](https://user-images.githubusercontent.com/2103975/102945818-2c715800-44bf-11eb-9218-a7e7538de9e8.png)
> 
> Maybe it's coming from your npm/yarn version, or your internet connection.
> 
> What is happening if you try again?

Same thing happens when I try again, not sure why
