### ISSUE TITLE
Error when create project

### ISSUE THREAD

**Issue by junnopham** [Kocal/vue-web-extension#652]
I have a problem while creating a new project and can't run the build command.
![2](https://user-images.githubusercontent.com/76786721/103556905-07c8a780-4ee5-11eb-8bbc-0bf0558a2ae6.PNG)

**Comment by Kocal** [comment]
Hi,

That's an ESLint issue, and it appears because the default generated fle [`background.js`](https://github.com/adambullmer/vue-cli-plugin-browser-extension/blob/master/generator/template/background/src/background.js#L4) declare a `tab` parameter that is not used.

To get rid of this issue, you can:
- remove `tab` from function's  parmaeters
- use `tab`
- ignore the error by disabling the rule `no-unused-vars`, see https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments
