### ISSUE TITLE
Uncaught (in promise) error in background page console when I click the browser action button. Content script is also not executing.

### ISSUE THREAD

**Issue by grandslammer** [Kocal/vue-web-extension#653]
Uncaught (in promise) error in background page console when I click the browser action button. Content script is also not executing.
Fresh project, I literally just did:
```
vue create --preset kocal/vue-web-extension my-extension
cd my-extension
npm run build
```
installed the extension, clicked the extension button in Chrome, and checked the background console.
I have retested several (created new projects) and it happens each time.

![Screenshot_10](https://user-images.githubusercontent.com/18541062/103584540-6c7e0500-4ed9-11eb-82d7-53eac65878bb.png)

**Comment by grandslammer** [comment]
Solved it:
In background.js, change line 5 from:
`file: "content-script.js",`

to:
`file: "js/content-script.js",`

The content script file path must be given from the extension root.

**Comment by Kocal** [comment]
Hi :wave: 

I think your issue is caused by this https://github.com/adambullmer/vue-cli-plugin-browser-extension/blob/master/generator/template/background/src/background.js#L10

And it seems that there is already an issue for that, see https://github.com/adambullmer/vue-cli-plugin-browser-extension/issues/95.

Opening a PR by changing `file: 'content-script.js',` to `file: 'js/content-script.js'` would be enough...
 Thanks!

**Comment by maxflex** [comment]
Thanks a lot, that helped

**Comment by brianberneker** [comment]
I've changed the file: 

`file: "content-script.js",`
to:
`file: "js/content-script.js",`

And now I still get the uncaught in promise error, but my "Hello from background" just keeps looping.
Any help would be appreciated!

![Screen Shot 2021-08-07 at 5 29 12 PM](https://user-images.githubusercontent.com/5161867/128614347-9632db0a-8431-4a06-b84a-7ba439c8b6fd.png)
